# Generated by Django 5.1.6 on 2025-03-06 09:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riggstore', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamesubmission',
            name='developer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='riggstore.developer'),
        ),
    ]
