# Generated by Django 5.1.7 on 2025-03-09 19:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riggstore', '0002_alter_gamesubmission_developer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamescreenshot',
            name='game',
        ),
        migrations.AddField(
            model_name='gamescreenshot',
            name='submission',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='screenshots', to='riggstore.gamesubmission'),
            preserve_default=False,
        ),
    ]
