# Generated by Django 5.1.7 on 2025-03-30 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riggstore', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='games',
            field=models.ManyToManyField(through='riggstore.OrderItem', to='riggstore.game'),
        ),
    ]
