# Generated by Django 5.1.6 on 2025-03-15 15:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riggstore', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamescreenshot',
            name='game',
        ),
        migrations.AddField(
            model_name='gamescreenshot',
            name='game_submission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='riggstore.gamesubmission'),
        ),
        migrations.AddField(
            model_name='gamesubmission',
            name='file_size',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gamesubmission',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='gamescreenshot',
            name='image',
            field=models.ImageField(upload_to='screenshots/'),
        ),
        migrations.AlterField(
            model_name='gamesubmission',
            name='developer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='riggstore.developer'),
        ),
        migrations.AlterField(
            model_name='gamesubmission',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
