# Generated by Django 5.1.6 on 2025-03-15 17:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riggstore', '0002_remove_gamescreenshot_game_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamesubmission',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='riggstore.category'),
            preserve_default=False,
        ),
    ]
