# Generated by Django 5.1.7 on 2025-03-31 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riggstore', '0003_downloadhistory_visible'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamesubmission',
            name='original_filename',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
