# Generated by Django 5.1.6 on 2025-03-15 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riggstore', '0003_gamesubmission_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamesubmission',
            name='category',
        ),
        migrations.AddField(
            model_name='gamesubmission',
            name='categories',
            field=models.ManyToManyField(to='riggstore.category'),
        ),
    ]
