# Generated by Django 5.1.7 on 2025-04-02 12:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riggstore', '0004_gamesubmission_original_filename'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamesubmission',
            name='developer_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='gamesubmission',
            name='discount_percentage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='gamesubmission',
            name='sale_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='gamesubmission',
            name='sale_type',
            field=models.CharField(blank=True, choices=[('summer', 'Summer Sale'), ('spring', 'Spring Sale'), ('winter', 'Winter Sale'), ('custom', 'Custom')], max_length=20),
        ),
    ]
