# Generated by Django 5.1.7 on 2025-04-18 02:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riggstore', '0005_gamesubmission_developer_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='game',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='official_community', to='riggstore.game'),
        ),
    ]
