# Generated by Django 5.1.6 on 2025-03-18 18:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riggstore', '0005_remove_game_category_game_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='submission',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='published_game', to='riggstore.gamesubmission'),
        ),
    ]
