# Generated by Django 5.1.7 on 2025-04-18 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riggstore', '0006_community_game'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamesubmission',
            name='community_description',
            field=models.TextField(blank=True, help_text='Optional custom description for your community', null=True),
        ),
        migrations.AddField(
            model_name='gamesubmission',
            name='community_name',
            field=models.CharField(blank=True, help_text="Optional custom title for your game's official community", max_length=100, null=True),
        ),
    ]
