# Generated by Django 5.1.7 on 2025-04-18 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riggstore', '0007_gamesubmission_community_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamesubmission',
            name='community_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gamesubmission',
            name='community_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
