# Generated by Django 5.1.6 on 2025-03-18 18:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riggstore', '0008_alter_gamescreenshot_game_submission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='submission',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='published_game', to='riggstore.gamesubmission'),
        ),
    ]
