# Generated by Django 5.2 on 2025-04-18 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('riggstore', '0008_alter_gamesubmission_community_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='community',
            name='game',
        ),
        migrations.RemoveField(
            model_name='gamesubmission',
            name='community_description',
        ),
        migrations.RemoveField(
            model_name='gamesubmission',
            name='community_name',
        ),
    ]
