# Generated by Django 5.2 on 2025-04-18 05:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riggstore', '0009_remove_community_game_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='game',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='official_community', to='riggstore.game'),
        ),
        migrations.AddField(
            model_name='gamesubmission',
            name='community_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gamesubmission',
            name='community_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
