# Generated by Django 5.2 on 2025-04-18 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riggstore', '0010_community_game_gamesubmission_community_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='pinned',
            field=models.BooleanField(default=False),
        ),
    ]
