# Generated by Django 5.2 on 2025-04-18 10:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riggstore', '0011_post_pinned'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='pinned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='pinned_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pinned_posts', to='riggstore.customer'),
        ),
    ]
