# Generated by Django 5.1.6 on 2025-03-25 18:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riggstore', '0012_developer_bank_account_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DownloadHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('downloaded_at', models.DateTimeField(auto_now_add=True)),
                ('download_type', models.CharField(choices=[('single', 'Single'), ('batch', 'Batch')], max_length=10)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='riggstore.game')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='downloads', to='riggstore.customer')),
            ],
            options={
                'verbose_name_plural': 'Download Histories',
                'ordering': ['-downloaded_at'],
            },
        ),
    ]
