# Generated by Django 5.2 on 2025-04-22 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riggstore', '0012_post_pinned_at_post_pinned_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='stripe_payment_intent_id',
            new_name='khalti_pidx',
        ),
        migrations.AddField(
            model_name='order',
            name='khalti_transaction_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
