# Generated by Django 5.1.6 on 2025-03-26 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riggstore', '0013_downloadhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamesubmission',
            name='download_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
