# Generated by Django 5.1.6 on 2025-03-28 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riggstore', '0015_emailverification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
