# Generated by Django 5.1.6 on 2025-03-28 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riggstore', '0018_alter_customer_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
